# Generated by Django 4.0.8 on 2022-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cluster_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
