# Generated by Django 4.0.8 on 2022-11-01 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=27, unique=True)),
                ('card_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=27)),
                ('machine_id', models.CharField(default='0', max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('last_recharge_amount', models.IntegerField(blank=True, null=True)),
                ('last_txn_volume', models.FloatField(blank=True, null=True)),
                ('last_txn_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_txn_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('machine_id', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=27)),
                ('order_status', models.CharField(choices=[('DONE_PAYMENT', 'DONE_PAYMENT'), ('DISPENSED', 'DISPENSED')], max_length=20)),
                ('amount', models.IntegerField()),
                ('volume_in_ml', models.FloatField()),
                ('sync_status', models.CharField(choices=[('SYNCED', 'SYNCED'), ('NOT_SYNCED', 'NOT_SYNCED')], max_length=20)),
                ('local_timestamp', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('machine_status', models.CharField(choices=[('OFFLINE', 'OFFLINE'), ('ONLINE', 'ONLINE')], max_length=20)),
                ('machine_location', models.CharField(max_length=100)),
                ('machine_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
    ]
