# Generated by Django 4.0.8 on 2022-11-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=27),
        ),
    ]
